### ISSUE TITLE
Crear canal en Telegram

### ISSUE THREAD

**Issue by juanteran** [stakewinner00/awesome-telegram-groups#6]
Es simple, creo que ya viene siendo hora que este `Indice` por así decirlo, debería tener un canal en telegram, es lo que opino @stkw0

**Comment by stkw0** [comment]
Algún motivo en concreto? 

Telegram no tiene un buscador de grupos, y esta repo de github es fácil de encontrarla por google, además que en github cualquiera puede contribuir sin mucho esfuerzo en cambio telegram no es tan abierto, además que en los canales que existen en telegram con indcies de grupos, a medida que se van añadiendo grupos los viejos ya no se ven, en cambio en un indice como este es más fácil ver el listado completo de grupos o buscarlos.
